bump:
  - readme.txt
  - site-reviews.php
dest:
  css: assets/styles/
  js: assets/scripts/
  lang: languages/
language:
  domain: site-reviews
  team: Gemini Labs <support@geminilabs.io>
  translator: Paul Ryley <paul@geminilabs.io>
scripts:
  mce-plugin.js: +/scripts/mce-plugin.js
  recaptcha.js: +/scripts/recaptcha.js
  site-reviews.js:
    - node_modules/star-rating.js/src/star-rating.js
    - +/scripts/public/ajax.js
    - +/scripts/public/excerpts.js
    - +/scripts/public/forms.js
    - +/scripts/public/pagination.js
    - +/scripts/public/recaptcha.js
    - +/scripts/site-reviews.js
  site-reviews-admin.js:
    - +/scripts/admin/ajax.js
    - +/scripts/admin/color-picker.js
    - +/scripts/admin/console.js
    - +/scripts/admin/forms.js
    - +/scripts/admin/notices.js
    - +/scripts/admin/pinned.js
    - +/scripts/admin/pointers.js
    - +/scripts/admin/search.js
    - +/scripts/admin/shortcode.js
    - +/scripts/admin/status.js
    - +/scripts/admin/tabs.js
    - +/scripts/admin/textarea-resize.js
    - +/scripts/site-reviews-admin.js
watch:
  js: +/scripts/**/*.js
  php:
    - config/*.php
    - plugin/**/*.php
    - views/**/*.php
    - '*.php'
  scss: +/styles/**/*.scss
